-- MySQL Script generated by MySQL Workbench
-- Sun Aug 23 17:27:47 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bugTracker
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bugTracker
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bugTracker` DEFAULT CHARACTER SET utf8 ;
USE `bugTracker` ;

-- -----------------------------------------------------
-- Table `bugTracker`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugTracker`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `userName` VARCHAR(256) NOT NULL,
  `password` VARCHAR(256) NOT NULL,
  `email` VARCHAR(256) NOT NULL,
  `name` VARCHAR(60) NOT NULL,
  `type` ENUM("admin", "basic", "develpor") NOT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `idUser_UNIQUE` (`idUser` ASC),
  UNIQUE INDEX `userName_UNIQUE` (`userName` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bugTracker`.`Project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugTracker`.`Project` (
  `idProject` INT NOT NULL AUTO_INCREMENT,
  `projectName` VARCHAR(45) NOT NULL,
  `description` VARCHAR(256) NOT NULL,
  `dateCreation` DATE NOT NULL,
  `terminated` TINYINT NOT NULL,
  PRIMARY KEY (`idProject`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bugTracker`.`ProjectWorker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugTracker`.`ProjectWorker` (
  `idUser` INT NOT NULL,
  `idProject` INT NOT NULL,
  `type` ENUM("owner", "admin", "coder", "tester") NOT NULL,
  PRIMARY KEY (`idUser`, `idProject`),
  INDEX `fk_User_has_Project_Project1_idx` (`idProject` ASC),
  INDEX `fk_User_has_Project_User1_idx` (`idUser` ASC),
  CONSTRAINT `fk_User_has_Project_User1`
    FOREIGN KEY (`idUser`)
    REFERENCES `bugTracker`.`User` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_User_has_Project_Project1`
    FOREIGN KEY (`idProject`)
    REFERENCES `bugTracker`.`Project` (`idProject`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bugTracker`.`Bug`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bugTracker`.`Bug` (
  `idBug` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(256) NOT NULL,
  `dateFound` DATE NOT NULL,
  `solved` TINYINT NOT NULL,
  `project` INT NOT NULL,
  `finder` INT NOT NULL,
  PRIMARY KEY (`idBug`),
  INDEX `fk_Bug_Project1_idx` (`project` ASC),
  INDEX `fk_Bug_User1_idx` (`finder` ASC),
  CONSTRAINT `fk_Bug_Project1`
    FOREIGN KEY (`project`)
    REFERENCES `bugTracker`.`Project` (`idProject`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Bug_User1`
    FOREIGN KEY (`finder`)
    REFERENCES `bugTracker`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
